/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const page: string;
declare const bgDecor: string;
declare const container: string;
declare const header: string;
declare const logo: string;
declare const title: string;
declare const subtitle: string;
declare const layout: string;
declare const setupCard: string;
declare const savedSection: string;
declare const sectionTitle: string;
declare const fieldGroup: string;
declare const fieldLabel: string;
declare const levelValue: string;
declare const classGrid: string;
declare const classBtn: string;
declare const classBtnActive: string;
declare const classBtnIcon: string;
declare const classBtnName: string;
declare const select: string;
declare const levelSlider: string;
declare const levelPips: string;
declare const levelPip: string;
declare const startBtn: string;
declare const savedList: string;
declare const savedCard: string;
declare const savedCardLeft: string;
declare const savedCardIcon: string;
declare const savedCardInfo: string;
declare const savedCardName: string;
declare const savedCardMeta: string;
declare const deleteSavedBtn: string;

export {
	page,
	bgDecor,
	container,
	header,
	logo,
	title,
	subtitle,
	layout,
	setupCard,
	savedSection,
	sectionTitle,
	fieldGroup,
	fieldLabel,
	levelValue,
	classGrid,
	classBtn,
	classBtnActive,
	classBtnIcon,
	classBtnName,
	select,
	levelSlider,
	levelPips,
	levelPip,
	startBtn,
	savedList,
	savedCard,
	savedCardLeft,
	savedCardIcon,
	savedCardInfo,
	savedCardName,
	savedCardMeta,
	deleteSavedBtn
};

declare const __default_export__: {
	page: typeof page;
	bgDecor: typeof bgDecor;
	container: typeof container;
	header: typeof header;
	logo: typeof logo;
	title: typeof title;
	subtitle: typeof subtitle;
	layout: typeof layout;
	setupCard: typeof setupCard;
	savedSection: typeof savedSection;
	sectionTitle: typeof sectionTitle;
	fieldGroup: typeof fieldGroup;
	fieldLabel: typeof fieldLabel;
	levelValue: typeof levelValue;
	classGrid: typeof classGrid;
	classBtn: typeof classBtn;
	classBtnActive: typeof classBtnActive;
	classBtnIcon: typeof classBtnIcon;
	classBtnName: typeof classBtnName;
	select: typeof select;
	levelSlider: typeof levelSlider;
	levelPips: typeof levelPips;
	levelPip: typeof levelPip;
	startBtn: typeof startBtn;
	savedList: typeof savedList;
	savedCard: typeof savedCard;
	savedCardLeft: typeof savedCardLeft;
	savedCardIcon: typeof savedCardIcon;
	savedCardInfo: typeof savedCardInfo;
	savedCardName: typeof savedCardName;
	savedCardMeta: typeof savedCardMeta;
	deleteSavedBtn: typeof deleteSavedBtn;
};
export default __default_export__;
