/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const page: string;
declare const topBar: string;
declare const topLeft: string;
declare const topCenter: string;
declare const topRight: string;
declare const backBtn: string;
declare const characterChip: string;
declare const classIcon: string;
declare const charInfo: string;
declare const charClass: string;
declare const charSubclass: string;
declare const nameDisplay: string;
declare const nameText: string;
declare const editIcon: string;
declare const nameEditRow: string;
declare const nameInput: string;
declare const nameConfirmBtn: string;
declare const actionBtn: string;
declare const savedBtn: string;
declare const shareBtnActive: string;
declare const animateBtnActive: string;
declare const edgeStyleGroup: string;
declare const edgeStyleBtn: string;
declare const edgeStyleBtnActive: string;
declare const topDivider: string;
declare const loadoutChip: string;
declare const loadoutChipArmed: string;
declare const concentrationChipArmed: string;
declare const concentrationChipConflict: string;
declare const concentrationCount: string;
declare const concentrationPopover: string;
declare const concentrationPopoverHeader: string;
declare const concentrationPopoverEmpty: string;
declare const concentrationPopoverList: string;
declare const concentrationPopoverItem: string;
declare const concentrationPopoverItemConflict: string;
declare const concentrationPopoverWarnIcon: string;
declare const economyChipActive: string;
declare const economyChipAlert: string;
declare const economyAlertBadge: string;
declare const economyPopover: string;
declare const economyPopoverHeader: string;
declare const economyPopoverCloseBtn: string;
declare const economyPopoverEmpty: string;
declare const economyWorstCase: string;
declare const economyBudgetGroup: string;
declare const economyActionBadge: string;
declare const economyActionBadgeSm: string;
declare const economyBudgetCount: string;
declare const economyBudgetStat: string;
declare const economyOk: string;
declare const economyOver: string;
declare const economyPathList: string;
declare const economyPathItem: string;
declare const economyPathItemOver: string;
declare const economyPathLabel: string;
declare const economyPathStatGroup: string;
declare const economyPathStat: string;
declare const economyPathNodes: string;
declare const economyPathMore: string;
declare const workspace: string;
declare const hint: string;
declare const slotsChipArmed: string;
declare const slotsSpentBadge: string;
declare const slotsPopover: string;
declare const slotsPopoverHeader: string;
declare const slotsRestoreBtn: string;
declare const slotsLevelList: string;
declare const slotsLevelRow: string;
declare const slotsLevelLabel: string;
declare const slotsCircles: string;
declare const slotCircle: string;
declare const slotCircleFilled: string;
declare const slotCircleEmpty: string;
declare const slotsCount: string;

export {
	page,
	topBar,
	topLeft,
	topCenter,
	topRight,
	backBtn,
	characterChip,
	classIcon,
	charInfo,
	charClass,
	charSubclass,
	nameDisplay,
	nameText,
	editIcon,
	nameEditRow,
	nameInput,
	nameConfirmBtn,
	actionBtn,
	savedBtn,
	shareBtnActive,
	animateBtnActive,
	edgeStyleGroup,
	edgeStyleBtn,
	edgeStyleBtnActive,
	topDivider,
	loadoutChip,
	loadoutChipArmed,
	concentrationChipArmed,
	concentrationChipConflict,
	concentrationCount,
	concentrationPopover,
	concentrationPopoverHeader,
	concentrationPopoverEmpty,
	concentrationPopoverList,
	concentrationPopoverItem,
	concentrationPopoverItemConflict,
	concentrationPopoverWarnIcon,
	economyChipActive,
	economyChipAlert,
	economyAlertBadge,
	economyPopover,
	economyPopoverHeader,
	economyPopoverCloseBtn,
	economyPopoverEmpty,
	economyWorstCase,
	economyBudgetGroup,
	economyActionBadge,
	economyActionBadgeSm,
	economyBudgetCount,
	economyBudgetStat,
	economyOk,
	economyOver,
	economyPathList,
	economyPathItem,
	economyPathItemOver,
	economyPathLabel,
	economyPathStatGroup,
	economyPathStat,
	economyPathNodes,
	economyPathMore,
	workspace,
	hint,
	slotsChipArmed,
	slotsSpentBadge,
	slotsPopover,
	slotsPopoverHeader,
	slotsRestoreBtn,
	slotsLevelList,
	slotsLevelRow,
	slotsLevelLabel,
	slotsCircles,
	slotCircle,
	slotCircleFilled,
	slotCircleEmpty,
	slotsCount
};

declare const __default_export__: {
	page: typeof page;
	topBar: typeof topBar;
	topLeft: typeof topLeft;
	topCenter: typeof topCenter;
	topRight: typeof topRight;
	backBtn: typeof backBtn;
	characterChip: typeof characterChip;
	classIcon: typeof classIcon;
	charInfo: typeof charInfo;
	charClass: typeof charClass;
	charSubclass: typeof charSubclass;
	nameDisplay: typeof nameDisplay;
	nameText: typeof nameText;
	editIcon: typeof editIcon;
	nameEditRow: typeof nameEditRow;
	nameInput: typeof nameInput;
	nameConfirmBtn: typeof nameConfirmBtn;
	actionBtn: typeof actionBtn;
	savedBtn: typeof savedBtn;
	shareBtnActive: typeof shareBtnActive;
	animateBtnActive: typeof animateBtnActive;
	edgeStyleGroup: typeof edgeStyleGroup;
	edgeStyleBtn: typeof edgeStyleBtn;
	edgeStyleBtnActive: typeof edgeStyleBtnActive;
	topDivider: typeof topDivider;
	loadoutChip: typeof loadoutChip;
	loadoutChipArmed: typeof loadoutChipArmed;
	concentrationChipArmed: typeof concentrationChipArmed;
	concentrationChipConflict: typeof concentrationChipConflict;
	concentrationCount: typeof concentrationCount;
	concentrationPopover: typeof concentrationPopover;
	concentrationPopoverHeader: typeof concentrationPopoverHeader;
	concentrationPopoverEmpty: typeof concentrationPopoverEmpty;
	concentrationPopoverList: typeof concentrationPopoverList;
	concentrationPopoverItem: typeof concentrationPopoverItem;
	concentrationPopoverItemConflict: typeof concentrationPopoverItemConflict;
	concentrationPopoverWarnIcon: typeof concentrationPopoverWarnIcon;
	economyChipActive: typeof economyChipActive;
	economyChipAlert: typeof economyChipAlert;
	economyAlertBadge: typeof economyAlertBadge;
	economyPopover: typeof economyPopover;
	economyPopoverHeader: typeof economyPopoverHeader;
	economyPopoverCloseBtn: typeof economyPopoverCloseBtn;
	economyPopoverEmpty: typeof economyPopoverEmpty;
	economyWorstCase: typeof economyWorstCase;
	economyBudgetGroup: typeof economyBudgetGroup;
	economyActionBadge: typeof economyActionBadge;
	economyActionBadgeSm: typeof economyActionBadgeSm;
	economyBudgetCount: typeof economyBudgetCount;
	economyBudgetStat: typeof economyBudgetStat;
	economyOk: typeof economyOk;
	economyOver: typeof economyOver;
	economyPathList: typeof economyPathList;
	economyPathItem: typeof economyPathItem;
	economyPathItemOver: typeof economyPathItemOver;
	economyPathLabel: typeof economyPathLabel;
	economyPathStatGroup: typeof economyPathStatGroup;
	economyPathStat: typeof economyPathStat;
	economyPathNodes: typeof economyPathNodes;
	economyPathMore: typeof economyPathMore;
	workspace: typeof workspace;
	hint: typeof hint;
	slotsChipArmed: typeof slotsChipArmed;
	slotsSpentBadge: typeof slotsSpentBadge;
	slotsPopover: typeof slotsPopover;
	slotsPopoverHeader: typeof slotsPopoverHeader;
	slotsRestoreBtn: typeof slotsRestoreBtn;
	slotsLevelList: typeof slotsLevelList;
	slotsLevelRow: typeof slotsLevelRow;
	slotsLevelLabel: typeof slotsLevelLabel;
	slotsCircles: typeof slotsCircles;
	slotCircle: typeof slotCircle;
	slotCircleFilled: typeof slotCircleFilled;
	slotCircleEmpty: typeof slotCircleEmpty;
	slotsCount: typeof slotsCount;
};
export default __default_export__;
