/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const page: string;
declare const topBar: string;
declare const topLeft: string;
declare const topCenter: string;
declare const topRight: string;
declare const backBtn: string;
declare const characterChip: string;
declare const classIcon: string;
declare const charInfo: string;
declare const charClass: string;
declare const charSubclass: string;
declare const nameDisplay: string;
declare const nameText: string;
declare const editIcon: string;
declare const nameEditRow: string;
declare const nameInput: string;
declare const nameConfirmBtn: string;
declare const actionBtn: string;
declare const savedBtn: string;
declare const shareBtnActive: string;
declare const animateBtnActive: string;
declare const edgeStyleGroup: string;
declare const edgeStyleBtn: string;
declare const edgeStyleBtnActive: string;
declare const topDivider: string;
declare const loadoutChip: string;
declare const loadoutChipArmed: string;
declare const workspace: string;
declare const hint: string;

export {
	page,
	topBar,
	topLeft,
	topCenter,
	topRight,
	backBtn,
	characterChip,
	classIcon,
	charInfo,
	charClass,
	charSubclass,
	nameDisplay,
	nameText,
	editIcon,
	nameEditRow,
	nameInput,
	nameConfirmBtn,
	actionBtn,
	savedBtn,
	shareBtnActive,
	animateBtnActive,
	edgeStyleGroup,
	edgeStyleBtn,
	edgeStyleBtnActive,
	topDivider,
	loadoutChip,
	loadoutChipArmed,
	workspace,
	hint
};

declare const __default_export__: {
	page: typeof page;
	topBar: typeof topBar;
	topLeft: typeof topLeft;
	topCenter: typeof topCenter;
	topRight: typeof topRight;
	backBtn: typeof backBtn;
	characterChip: typeof characterChip;
	classIcon: typeof classIcon;
	charInfo: typeof charInfo;
	charClass: typeof charClass;
	charSubclass: typeof charSubclass;
	nameDisplay: typeof nameDisplay;
	nameText: typeof nameText;
	editIcon: typeof editIcon;
	nameEditRow: typeof nameEditRow;
	nameInput: typeof nameInput;
	nameConfirmBtn: typeof nameConfirmBtn;
	actionBtn: typeof actionBtn;
	savedBtn: typeof savedBtn;
	shareBtnActive: typeof shareBtnActive;
	animateBtnActive: typeof animateBtnActive;
	edgeStyleGroup: typeof edgeStyleGroup;
	edgeStyleBtn: typeof edgeStyleBtn;
	edgeStyleBtnActive: typeof edgeStyleBtnActive;
	topDivider: typeof topDivider;
	loadoutChip: typeof loadoutChip;
	loadoutChipArmed: typeof loadoutChipArmed;
	workspace: typeof workspace;
	hint: typeof hint;
};
export default __default_export__;
