/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const page: string;
declare const topBar: string;
declare const topLeft: string;
declare const topCenter: string;
declare const topRight: string;
declare const backBtn: string;
declare const characterChip: string;
declare const classIcon: string;
declare const charInfo: string;
declare const charClass: string;
declare const charSubclass: string;
declare const nameDisplay: string;
declare const nameText: string;
declare const editIcon: string;
declare const nameEditRow: string;
declare const nameInput: string;
declare const nameConfirmBtn: string;
declare const actionBtn: string;
declare const savedBtn: string;
declare const shareBtnActive: string;
declare const animateBtnActive: string;
declare const edgeStyleGroup: string;
declare const edgeStyleBtn: string;
declare const edgeStyleBtnActive: string;
declare const topDivider: string;
declare const loadoutChip: string;
declare const loadoutChipArmed: string;
declare const concentrationChipArmed: string;
declare const groupsChipArmed: string;
declare const groupsCount: string;
declare const groupsPopover: string;
declare const groupsPopoverHeader: string;
declare const groupsPopoverEmpty: string;
declare const groupsPopoverList: string;
declare const groupsPopoverItem: string;
declare const groupsColorDot: string;
declare const groupsSelectBtn: string;
declare const groupsMemberCount: string;
declare const groupsDisbandBtn: string;
declare const concentrationChipConflict: string;
declare const concentrationCount: string;
declare const concentrationPopover: string;
declare const concentrationPopoverHeader: string;
declare const concentrationPopoverEmpty: string;
declare const concentrationPopoverList: string;
declare const concentrationPopoverItem: string;
declare const concentrationPopoverItemConflict: string;
declare const concentrationPopoverWarnIcon: string;
declare const economyChipActive: string;
declare const economyChipAlert: string;
declare const economyAlertBadge: string;
declare const economyPopover: string;
declare const economyPopoverHeader: string;
declare const economyPopoverCloseBtn: string;
declare const economyPopoverEmpty: string;
declare const economyWorstCase: string;
declare const economyBudgetGroup: string;
declare const economyActionBadge: string;
declare const economyActionBadgeSm: string;
declare const economyBudgetCount: string;
declare const economyBudgetStat: string;
declare const economyOk: string;
declare const economyOver: string;
declare const economyPathList: string;
declare const economyPathItem: string;
declare const economyPathItemOver: string;
declare const economyPathLabel: string;
declare const economyPathStatGroup: string;
declare const economyPathStat: string;
declare const economyPathNodes: string;
declare const economyPathMore: string;
declare const workspace: string;
declare const hint: string;
declare const slotsChipArmed: string;
declare const slotsSpentBadge: string;
declare const slotsPopover: string;
declare const slotsPopoverHeader: string;
declare const slotsRestoreBtn: string;
declare const slotsLevelList: string;
declare const slotsLevelRow: string;
declare const slotsLevelLabel: string;
declare const slotsCircles: string;
declare const slotCircle: string;
declare const slotCircleFilled: string;
declare const slotCircleEmpty: string;
declare const slotsCount: string;
declare const exportMenuWrapper: string;
declare const exportMenu: string;
declare const exportMenuItem: string;
declare const exportMenuItemActive: string;
declare const exportMenuItemSuccess: string;
declare const exportMenuItemKbd: string;
declare const exportMenuItemCheck: string;
declare const exportMenuDivider: string;
declare const exportMenuTabHeader: string;
declare const exportMenuTabRow: string;
declare const exportMenuTabActive: string;
declare const exportMenuTabSwitch: string;
declare const exportMenuTabName: string;
declare const exportMenuTabMeta: string;
declare const exportMenuTabClose: string;
declare const panelToggleBtn: string;
declare const panelToggleBtnActive: string;
declare const drawerOverlay: string;
declare const libraryFab: string;
declare const selectModeToggle: string;
declare const hintHidden: string;
declare const selectModeToggleActive: string;

export {
	page,
	topBar,
	topLeft,
	topCenter,
	topRight,
	backBtn,
	characterChip,
	classIcon,
	charInfo,
	charClass,
	charSubclass,
	nameDisplay,
	nameText,
	editIcon,
	nameEditRow,
	nameInput,
	nameConfirmBtn,
	actionBtn,
	savedBtn,
	shareBtnActive,
	animateBtnActive,
	edgeStyleGroup,
	edgeStyleBtn,
	edgeStyleBtnActive,
	topDivider,
	loadoutChip,
	loadoutChipArmed,
	concentrationChipArmed,
	groupsChipArmed,
	groupsCount,
	groupsPopover,
	groupsPopoverHeader,
	groupsPopoverEmpty,
	groupsPopoverList,
	groupsPopoverItem,
	groupsColorDot,
	groupsSelectBtn,
	groupsMemberCount,
	groupsDisbandBtn,
	concentrationChipConflict,
	concentrationCount,
	concentrationPopover,
	concentrationPopoverHeader,
	concentrationPopoverEmpty,
	concentrationPopoverList,
	concentrationPopoverItem,
	concentrationPopoverItemConflict,
	concentrationPopoverWarnIcon,
	economyChipActive,
	economyChipAlert,
	economyAlertBadge,
	economyPopover,
	economyPopoverHeader,
	economyPopoverCloseBtn,
	economyPopoverEmpty,
	economyWorstCase,
	economyBudgetGroup,
	economyActionBadge,
	economyActionBadgeSm,
	economyBudgetCount,
	economyBudgetStat,
	economyOk,
	economyOver,
	economyPathList,
	economyPathItem,
	economyPathItemOver,
	economyPathLabel,
	economyPathStatGroup,
	economyPathStat,
	economyPathNodes,
	economyPathMore,
	workspace,
	hint,
	slotsChipArmed,
	slotsSpentBadge,
	slotsPopover,
	slotsPopoverHeader,
	slotsRestoreBtn,
	slotsLevelList,
	slotsLevelRow,
	slotsLevelLabel,
	slotsCircles,
	slotCircle,
	slotCircleFilled,
	slotCircleEmpty,
	slotsCount,
	exportMenuWrapper,
	exportMenu,
	exportMenuItem,
	exportMenuItemActive,
	exportMenuItemSuccess,
	exportMenuItemKbd,
	exportMenuItemCheck,
	exportMenuDivider,
	exportMenuTabHeader,
	exportMenuTabRow,
	exportMenuTabActive,
	exportMenuTabSwitch,
	exportMenuTabName,
	exportMenuTabMeta,
	exportMenuTabClose,
	panelToggleBtn,
	panelToggleBtnActive,
	drawerOverlay,
	libraryFab,
	selectModeToggle,
	hintHidden,
	selectModeToggleActive
};

declare const __default_export__: {
	page: typeof page;
	topBar: typeof topBar;
	topLeft: typeof topLeft;
	topCenter: typeof topCenter;
	topRight: typeof topRight;
	backBtn: typeof backBtn;
	characterChip: typeof characterChip;
	classIcon: typeof classIcon;
	charInfo: typeof charInfo;
	charClass: typeof charClass;
	charSubclass: typeof charSubclass;
	nameDisplay: typeof nameDisplay;
	nameText: typeof nameText;
	editIcon: typeof editIcon;
	nameEditRow: typeof nameEditRow;
	nameInput: typeof nameInput;
	nameConfirmBtn: typeof nameConfirmBtn;
	actionBtn: typeof actionBtn;
	savedBtn: typeof savedBtn;
	shareBtnActive: typeof shareBtnActive;
	animateBtnActive: typeof animateBtnActive;
	edgeStyleGroup: typeof edgeStyleGroup;
	edgeStyleBtn: typeof edgeStyleBtn;
	edgeStyleBtnActive: typeof edgeStyleBtnActive;
	topDivider: typeof topDivider;
	loadoutChip: typeof loadoutChip;
	loadoutChipArmed: typeof loadoutChipArmed;
	concentrationChipArmed: typeof concentrationChipArmed;
	groupsChipArmed: typeof groupsChipArmed;
	groupsCount: typeof groupsCount;
	groupsPopover: typeof groupsPopover;
	groupsPopoverHeader: typeof groupsPopoverHeader;
	groupsPopoverEmpty: typeof groupsPopoverEmpty;
	groupsPopoverList: typeof groupsPopoverList;
	groupsPopoverItem: typeof groupsPopoverItem;
	groupsColorDot: typeof groupsColorDot;
	groupsSelectBtn: typeof groupsSelectBtn;
	groupsMemberCount: typeof groupsMemberCount;
	groupsDisbandBtn: typeof groupsDisbandBtn;
	concentrationChipConflict: typeof concentrationChipConflict;
	concentrationCount: typeof concentrationCount;
	concentrationPopover: typeof concentrationPopover;
	concentrationPopoverHeader: typeof concentrationPopoverHeader;
	concentrationPopoverEmpty: typeof concentrationPopoverEmpty;
	concentrationPopoverList: typeof concentrationPopoverList;
	concentrationPopoverItem: typeof concentrationPopoverItem;
	concentrationPopoverItemConflict: typeof concentrationPopoverItemConflict;
	concentrationPopoverWarnIcon: typeof concentrationPopoverWarnIcon;
	economyChipActive: typeof economyChipActive;
	economyChipAlert: typeof economyChipAlert;
	economyAlertBadge: typeof economyAlertBadge;
	economyPopover: typeof economyPopover;
	economyPopoverHeader: typeof economyPopoverHeader;
	economyPopoverCloseBtn: typeof economyPopoverCloseBtn;
	economyPopoverEmpty: typeof economyPopoverEmpty;
	economyWorstCase: typeof economyWorstCase;
	economyBudgetGroup: typeof economyBudgetGroup;
	economyActionBadge: typeof economyActionBadge;
	economyActionBadgeSm: typeof economyActionBadgeSm;
	economyBudgetCount: typeof economyBudgetCount;
	economyBudgetStat: typeof economyBudgetStat;
	economyOk: typeof economyOk;
	economyOver: typeof economyOver;
	economyPathList: typeof economyPathList;
	economyPathItem: typeof economyPathItem;
	economyPathItemOver: typeof economyPathItemOver;
	economyPathLabel: typeof economyPathLabel;
	economyPathStatGroup: typeof economyPathStatGroup;
	economyPathStat: typeof economyPathStat;
	economyPathNodes: typeof economyPathNodes;
	economyPathMore: typeof economyPathMore;
	workspace: typeof workspace;
	hint: typeof hint;
	slotsChipArmed: typeof slotsChipArmed;
	slotsSpentBadge: typeof slotsSpentBadge;
	slotsPopover: typeof slotsPopover;
	slotsPopoverHeader: typeof slotsPopoverHeader;
	slotsRestoreBtn: typeof slotsRestoreBtn;
	slotsLevelList: typeof slotsLevelList;
	slotsLevelRow: typeof slotsLevelRow;
	slotsLevelLabel: typeof slotsLevelLabel;
	slotsCircles: typeof slotsCircles;
	slotCircle: typeof slotCircle;
	slotCircleFilled: typeof slotCircleFilled;
	slotCircleEmpty: typeof slotCircleEmpty;
	slotsCount: typeof slotsCount;
	exportMenuWrapper: typeof exportMenuWrapper;
	exportMenu: typeof exportMenu;
	exportMenuItem: typeof exportMenuItem;
	exportMenuItemActive: typeof exportMenuItemActive;
	exportMenuItemSuccess: typeof exportMenuItemSuccess;
	exportMenuItemKbd: typeof exportMenuItemKbd;
	exportMenuItemCheck: typeof exportMenuItemCheck;
	exportMenuDivider: typeof exportMenuDivider;
	exportMenuTabHeader: typeof exportMenuTabHeader;
	exportMenuTabRow: typeof exportMenuTabRow;
	exportMenuTabActive: typeof exportMenuTabActive;
	exportMenuTabSwitch: typeof exportMenuTabSwitch;
	exportMenuTabName: typeof exportMenuTabName;
	exportMenuTabMeta: typeof exportMenuTabMeta;
	exportMenuTabClose: typeof exportMenuTabClose;
	panelToggleBtn: typeof panelToggleBtn;
	panelToggleBtnActive: typeof panelToggleBtnActive;
	drawerOverlay: typeof drawerOverlay;
	libraryFab: typeof libraryFab;
	selectModeToggle: typeof selectModeToggle;
	hintHidden: typeof hintHidden;
	selectModeToggleActive: typeof selectModeToggleActive;
};
export default __default_export__;
