/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const bundleBadgeWrapper: string;
declare const bundleBadge: string;
declare const bundleTooltip: string;
declare const bundleTooltipItem: string;

export {
	bundleBadgeWrapper,
	bundleBadge,
	bundleTooltip,
	bundleTooltipItem
};

declare const __default_export__: {
	bundleBadgeWrapper: typeof bundleBadgeWrapper;
	bundleBadge: typeof bundleBadge;
	bundleTooltip: typeof bundleTooltip;
	bundleTooltipItem: typeof bundleTooltipItem;
};
export default __default_export__;
