/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const labelPillWrapper: string;
declare const labelPill: string;
declare const emptyPill: string;
declare const labelInput: string;

export {
	labelPillWrapper,
	labelPill,
	emptyPill,
	labelInput
};

declare const __default_export__: {
	labelPillWrapper: typeof labelPillWrapper;
	labelPill: typeof labelPill;
	emptyPill: typeof emptyPill;
	labelInput: typeof labelInput;
};
export default __default_export__;
