/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const canvasWrapper: string;
declare const concentrationWarning: string;
declare const concentrationWarningIcon: string;
declare const controls: string;
declare const minimap: string;

export {
	canvasWrapper,
	concentrationWarning,
	concentrationWarningIcon,
	controls,
	minimap
};

declare const __default_export__: {
	canvasWrapper: typeof canvasWrapper;
	concentrationWarning: typeof concentrationWarning;
	concentrationWarningIcon: typeof concentrationWarningIcon;
	controls: typeof controls;
	minimap: typeof minimap;
};
export default __default_export__;
