/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const canvasWrapper: string;
declare const concentrationWarning: string;
declare const concentrationWarningIcon: string;
declare const controls: string;
declare const minimapWrapper: string;
declare const minimapCollapsed: string;
declare const minimap: string;
declare const minimapToggle: string;

export {
	canvasWrapper,
	concentrationWarning,
	concentrationWarningIcon,
	controls,
	minimapWrapper,
	minimapCollapsed,
	minimap,
	minimapToggle
};

declare const __default_export__: {
	canvasWrapper: typeof canvasWrapper;
	concentrationWarning: typeof concentrationWarning;
	concentrationWarningIcon: typeof concentrationWarningIcon;
	controls: typeof controls;
	minimapWrapper: typeof minimapWrapper;
	minimapCollapsed: typeof minimapCollapsed;
	minimap: typeof minimap;
	minimapToggle: typeof minimapToggle;
};
export default __default_export__;
