/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const overlay: string;
declare const panel: string;
declare const header: string;
declare const title: string;
declare const closeBtn: string;
declare const body: string;
declare const row: string;
declare const rowLabel: string;
declare const select: string;
declare const checkRow: string;
declare const checkbox: string;
declare const checkLabel: string;
declare const autoTag: string;
declare const offHandGroup: string;
declare const offHandBtn: string;
declare const offHandBtnActive: string;
declare const warning: string;
declare const hint: string;
declare const footer: string;
declare const clearBtn: string;
declare const saveBtn: string;
declare const widerPanel: string;
declare const formBody: string;
declare const formLabel: string;
declare const formInput: string;
declare const formRow: string;
declare const formLabelFlex: string;
declare const formLabelFlex2: string;
declare const propertiesGrid: string;
declare const propCheckLabel: string;
declare const iconPickerGrid: string;
declare const iconPickerBtn: string;
declare const iconPickerBtnSelected: string;
declare const addWeaponRow: string;
declare const addWeaponBtn: string;

export {
	overlay,
	panel,
	header,
	title,
	closeBtn,
	body,
	row,
	rowLabel,
	select,
	checkRow,
	checkbox,
	checkLabel,
	autoTag,
	offHandGroup,
	offHandBtn,
	offHandBtnActive,
	warning,
	hint,
	footer,
	clearBtn,
	saveBtn,
	widerPanel,
	formBody,
	formLabel,
	formInput,
	formRow,
	formLabelFlex,
	formLabelFlex2,
	propertiesGrid,
	propCheckLabel,
	iconPickerGrid,
	iconPickerBtn,
	iconPickerBtnSelected,
	addWeaponRow,
	addWeaponBtn
};

declare const __default_export__: {
	overlay: typeof overlay;
	panel: typeof panel;
	header: typeof header;
	title: typeof title;
	closeBtn: typeof closeBtn;
	body: typeof body;
	row: typeof row;
	rowLabel: typeof rowLabel;
	select: typeof select;
	checkRow: typeof checkRow;
	checkbox: typeof checkbox;
	checkLabel: typeof checkLabel;
	autoTag: typeof autoTag;
	offHandGroup: typeof offHandGroup;
	offHandBtn: typeof offHandBtn;
	offHandBtnActive: typeof offHandBtnActive;
	warning: typeof warning;
	hint: typeof hint;
	footer: typeof footer;
	clearBtn: typeof clearBtn;
	saveBtn: typeof saveBtn;
	widerPanel: typeof widerPanel;
	formBody: typeof formBody;
	formLabel: typeof formLabel;
	formInput: typeof formInput;
	formRow: typeof formRow;
	formLabelFlex: typeof formLabelFlex;
	formLabelFlex2: typeof formLabelFlex2;
	propertiesGrid: typeof propertiesGrid;
	propCheckLabel: typeof propCheckLabel;
	iconPickerGrid: typeof iconPickerGrid;
	iconPickerBtn: typeof iconPickerBtn;
	iconPickerBtnSelected: typeof iconPickerBtnSelected;
	addWeaponRow: typeof addWeaponRow;
	addWeaponBtn: typeof addWeaponBtn;
};
export default __default_export__;
