/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const panel: string;
declare const header: string;
declare const label: string;
declare const closeBtn: string;
declare const actions: string;
declare const deleteBtn: string;
declare const deselectBtn: string;

export {
	panel,
	header,
	label,
	closeBtn,
	actions,
	deleteBtn,
	deselectBtn
};

declare const __default_export__: {
	panel: typeof panel;
	header: typeof header;
	label: typeof label;
	closeBtn: typeof closeBtn;
	actions: typeof actions;
	deleteBtn: typeof deleteBtn;
	deselectBtn: typeof deselectBtn;
};
export default __default_export__;
