/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const panel: string;
declare const header: string;
declare const label: string;
declare const closeBtn: string;
declare const actions: string;
declare const deleteBtn: string;
declare const deselectBtn: string;
declare const groupSection: string;
declare const groupNameInput: string;
declare const groupBtn: string;
declare const groupInfo: string;
declare const groupInfoLabel: string;
declare const disbandBtn: string;

export {
	panel,
	header,
	label,
	closeBtn,
	actions,
	deleteBtn,
	deselectBtn,
	groupSection,
	groupNameInput,
	groupBtn,
	groupInfo,
	groupInfoLabel,
	disbandBtn
};

declare const __default_export__: {
	panel: typeof panel;
	header: typeof header;
	label: typeof label;
	closeBtn: typeof closeBtn;
	actions: typeof actions;
	deleteBtn: typeof deleteBtn;
	deselectBtn: typeof deselectBtn;
	groupSection: typeof groupSection;
	groupNameInput: typeof groupNameInput;
	groupBtn: typeof groupBtn;
	groupInfo: typeof groupInfo;
	groupInfoLabel: typeof groupInfoLabel;
	disbandBtn: typeof disbandBtn;
};
export default __default_export__;
