/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const panel: string;
declare const header: string;
declare const headerLeft: string;
declare const nodeTypeLabel: string;
declare const actionTypeBadge: string;
declare const closeBtn: string;
declare const body: string;
declare const infoRow: string;
declare const schoolChip: string;
declare const damageChip: string;
declare const field: string;
declare const fieldLabel: string;
declare const fieldRow: string;
declare const fieldInput: string;
declare const pillRow: string;
declare const infoPill: string;
declare const descText: string;
declare const notesTextarea: string;
declare const footer: string;
declare const deleteBtn: string;
declare const hint: string;

export {
	panel,
	header,
	headerLeft,
	nodeTypeLabel,
	actionTypeBadge,
	closeBtn,
	body,
	infoRow,
	schoolChip,
	damageChip,
	field,
	fieldLabel,
	fieldRow,
	fieldInput,
	pillRow,
	infoPill,
	descText,
	notesTextarea,
	footer,
	deleteBtn,
	hint
};

declare const __default_export__: {
	panel: typeof panel;
	header: typeof header;
	headerLeft: typeof headerLeft;
	nodeTypeLabel: typeof nodeTypeLabel;
	actionTypeBadge: typeof actionTypeBadge;
	closeBtn: typeof closeBtn;
	body: typeof body;
	infoRow: typeof infoRow;
	schoolChip: typeof schoolChip;
	damageChip: typeof damageChip;
	field: typeof field;
	fieldLabel: typeof fieldLabel;
	fieldRow: typeof fieldRow;
	fieldInput: typeof fieldInput;
	pillRow: typeof pillRow;
	infoPill: typeof infoPill;
	descText: typeof descText;
	notesTextarea: typeof notesTextarea;
	footer: typeof footer;
	deleteBtn: typeof deleteBtn;
	hint: typeof hint;
};
export default __default_export__;
