/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const panel: string;
declare const header: string;
declare const headerLeft: string;
declare const nodeTypeLabel: string;
declare const actionTypeBadge: string;
declare const closeBtn: string;
declare const body: string;
declare const infoRow: string;
declare const schoolChip: string;
declare const damageChip: string;
declare const field: string;
declare const fieldLabel: string;
declare const fieldRow: string;
declare const fieldInput: string;
declare const pillRow: string;
declare const infoPill: string;
declare const descText: string;
declare const notesTextarea: string;
declare const footer: string;
declare const deleteBtn: string;
declare const hint: string;
declare const variantsHeader: string;
declare const addVariantBtn: string;
declare const variantsList: string;
declare const variantItem: string;
declare const variantItemLabel: string;
declare const variantItemBadges: string;
declare const variantLevelBadge: string;
declare const variantActionBadge: string;
declare const variantDamageBadge: string;
declare const removeVariantBtn: string;
declare const variantSearch: string;
declare const variantSearchInput: string;
declare const variantSearchResults: string;
declare const variantResultRow: string;
declare const variantResultAdded: string;
declare const variantResultLabel: string;
declare const variantResultBadge: string;
declare const variantSearchEmpty: string;

export {
	panel,
	header,
	headerLeft,
	nodeTypeLabel,
	actionTypeBadge,
	closeBtn,
	body,
	infoRow,
	schoolChip,
	damageChip,
	field,
	fieldLabel,
	fieldRow,
	fieldInput,
	pillRow,
	infoPill,
	descText,
	notesTextarea,
	footer,
	deleteBtn,
	hint,
	variantsHeader,
	addVariantBtn,
	variantsList,
	variantItem,
	variantItemLabel,
	variantItemBadges,
	variantLevelBadge,
	variantActionBadge,
	variantDamageBadge,
	removeVariantBtn,
	variantSearch,
	variantSearchInput,
	variantSearchResults,
	variantResultRow,
	variantResultAdded,
	variantResultLabel,
	variantResultBadge,
	variantSearchEmpty
};

declare const __default_export__: {
	panel: typeof panel;
	header: typeof header;
	headerLeft: typeof headerLeft;
	nodeTypeLabel: typeof nodeTypeLabel;
	actionTypeBadge: typeof actionTypeBadge;
	closeBtn: typeof closeBtn;
	body: typeof body;
	infoRow: typeof infoRow;
	schoolChip: typeof schoolChip;
	damageChip: typeof damageChip;
	field: typeof field;
	fieldLabel: typeof fieldLabel;
	fieldRow: typeof fieldRow;
	fieldInput: typeof fieldInput;
	pillRow: typeof pillRow;
	infoPill: typeof infoPill;
	descText: typeof descText;
	notesTextarea: typeof notesTextarea;
	footer: typeof footer;
	deleteBtn: typeof deleteBtn;
	hint: typeof hint;
	variantsHeader: typeof variantsHeader;
	addVariantBtn: typeof addVariantBtn;
	variantsList: typeof variantsList;
	variantItem: typeof variantItem;
	variantItemLabel: typeof variantItemLabel;
	variantItemBadges: typeof variantItemBadges;
	variantLevelBadge: typeof variantLevelBadge;
	variantActionBadge: typeof variantActionBadge;
	variantDamageBadge: typeof variantDamageBadge;
	removeVariantBtn: typeof removeVariantBtn;
	variantSearch: typeof variantSearch;
	variantSearchInput: typeof variantSearchInput;
	variantSearchResults: typeof variantSearchResults;
	variantResultRow: typeof variantResultRow;
	variantResultAdded: typeof variantResultAdded;
	variantResultLabel: typeof variantResultLabel;
	variantResultBadge: typeof variantResultBadge;
	variantSearchEmpty: typeof variantSearchEmpty;
};
export default __default_export__;
