/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const panel: string;
declare const panelHeader: string;
declare const characterChip: string;
declare const classIcon: string;
declare const characterInfo: string;
declare const characterClass: string;
declare const characterLevel: string;
declare const templates: string;
declare const templatesLabel: string;
declare const templateGrid: string;
declare const template: string;
declare const templateIcon: string;
declare const templateLabel: string;
declare const searchWrapper: string;
declare const searchIcon: string;
declare const searchInput: string;
declare const clearSearch: string;
declare const tabs: string;
declare const tab: string;
declare const activeTab: string;
declare const levelFilters: string;
declare const levelChip: string;
declare const activeLevelChip: string;
declare const cardList: string;
declare const emptyState: string;
declare const panelFooter: string;
declare const addCustomBtn: string;
declare const modalOverlay: string;
declare const modal: string;
declare const modalHeader: string;
declare const modalTitle: string;
declare const closeBtn: string;
declare const modalForm: string;
declare const formLabel: string;
declare const formInput: string;
declare const formSelect: string;
declare const formTextarea: string;
declare const formActions: string;
declare const cancelBtn: string;
declare const submitBtn: string;

export {
	panel,
	panelHeader,
	characterChip,
	classIcon,
	characterInfo,
	characterClass,
	characterLevel,
	templates,
	templatesLabel,
	templateGrid,
	template,
	templateIcon,
	templateLabel,
	searchWrapper,
	searchIcon,
	searchInput,
	clearSearch,
	tabs,
	tab,
	activeTab,
	levelFilters,
	levelChip,
	activeLevelChip,
	cardList,
	emptyState,
	panelFooter,
	addCustomBtn,
	modalOverlay,
	modal,
	modalHeader,
	modalTitle,
	closeBtn,
	modalForm,
	formLabel,
	formInput,
	formSelect,
	formTextarea,
	formActions,
	cancelBtn,
	submitBtn
};

declare const __default_export__: {
	panel: typeof panel;
	panelHeader: typeof panelHeader;
	characterChip: typeof characterChip;
	classIcon: typeof classIcon;
	characterInfo: typeof characterInfo;
	characterClass: typeof characterClass;
	characterLevel: typeof characterLevel;
	templates: typeof templates;
	templatesLabel: typeof templatesLabel;
	templateGrid: typeof templateGrid;
	template: typeof template;
	templateIcon: typeof templateIcon;
	templateLabel: typeof templateLabel;
	searchWrapper: typeof searchWrapper;
	searchIcon: typeof searchIcon;
	searchInput: typeof searchInput;
	clearSearch: typeof clearSearch;
	tabs: typeof tabs;
	tab: typeof tab;
	activeTab: typeof activeTab;
	levelFilters: typeof levelFilters;
	levelChip: typeof levelChip;
	activeLevelChip: typeof activeLevelChip;
	cardList: typeof cardList;
	emptyState: typeof emptyState;
	panelFooter: typeof panelFooter;
	addCustomBtn: typeof addCustomBtn;
	modalOverlay: typeof modalOverlay;
	modal: typeof modal;
	modalHeader: typeof modalHeader;
	modalTitle: typeof modalTitle;
	closeBtn: typeof closeBtn;
	modalForm: typeof modalForm;
	formLabel: typeof formLabel;
	formInput: typeof formInput;
	formSelect: typeof formSelect;
	formTextarea: typeof formTextarea;
	formActions: typeof formActions;
	cancelBtn: typeof cancelBtn;
	submitBtn: typeof submitBtn;
};
export default __default_export__;
