/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const panel: string;
declare const panelCollapsed: string;
declare const panelSliver: string;
declare const collapseBtn: string;
declare const sliverArrow: string;
declare const sliverLabel: string;
declare const panelHeader: string;
declare const characterChip: string;
declare const classIcon: string;
declare const characterInfo: string;
declare const characterClass: string;
declare const characterLevel: string;
declare const templates: string;
declare const templatesLabel: string;
declare const templateGrid: string;
declare const template: string;
declare const templateIcon: string;
declare const templateLabel: string;
declare const searchWrapper: string;
declare const searchIcon: string;
declare const searchInput: string;
declare const clearSearch: string;
declare const tabs: string;
declare const tab: string;
declare const activeTab: string;
declare const levelFilters: string;
declare const levelChip: string;
declare const levelChipCircle: string;
declare const activeLevelChip: string;
declare const sourceFilters: string;
declare const sourceChip: string;
declare const activeSourceChip: string;
declare const suggestedGroups: string;
declare const suggestedGroupsLabel: string;
declare const suggestedGroupsList: string;
declare const groupChip: string;
declare const groupChipLabel: string;
declare const groupChipCount: string;
declare const weaponsSection: string;
declare const weaponsSectionLabel: string;
declare const noWeaponCard: string;
declare const noWeaponInfo: string;
declare const noWeaponLabel: string;
declare const noWeaponHint: string;
declare const cardList: string;
declare const conditionsSection: string;
declare const conditionsSectionHeader: string;
declare const conditionsSectionLabel: string;
declare const conditionAffectsToggle: string;
declare const conditionAffectsBtn: string;
declare const conditionAffectsBtnActive: string;
declare const conditionChips: string;
declare const conditionChip: string;
declare const conditionChipIcon: string;
declare const conditionChipLabel: string;
declare const conditionsTab: string;
declare const conditionAffectsRow: string;
declare const conditionAffectsRowLabel: string;
declare const conditionChipsFull: string;
declare const conditionChipFull: string;
declare const conditionChipFullIcon: string;
declare const conditionChipFullLabel: string;
declare const emptyState: string;
declare const shieldCard: string;
declare const shieldIcon: string;
declare const shieldLabel: string;
declare const shieldAc: string;
declare const panelFooter: string;
declare const companionsTab: string;
declare const companionCard: string;
declare const companionCardHeader: string;
declare const companionCardTypeIcon: string;
declare const companionCardName: string;
declare const companionCardTypeBadge: string;
declare const companionCardStats: string;
declare const companionCardStat: string;
declare const companionCardStatLabel: string;
declare const companionCardStatValue: string;
declare const companionCardMinLevel: string;
declare const addCustomBtn: string;
declare const modalOverlay: string;
declare const modal: string;
declare const modalHeader: string;
declare const modalTitle: string;
declare const closeBtn: string;
declare const modalForm: string;
declare const formLabel: string;
declare const formInput: string;
declare const formSelect: string;
declare const formTextarea: string;
declare const formActions: string;
declare const cancelBtn: string;
declare const submitBtn: string;
declare const dragHandle: string;
declare const dragHandleBar: string;
declare const panelOpen: string;

export {
	panel,
	panelCollapsed,
	panelSliver,
	collapseBtn,
	sliverArrow,
	sliverLabel,
	panelHeader,
	characterChip,
	classIcon,
	characterInfo,
	characterClass,
	characterLevel,
	templates,
	templatesLabel,
	templateGrid,
	template,
	templateIcon,
	templateLabel,
	searchWrapper,
	searchIcon,
	searchInput,
	clearSearch,
	tabs,
	tab,
	activeTab,
	levelFilters,
	levelChip,
	levelChipCircle,
	activeLevelChip,
	sourceFilters,
	sourceChip,
	activeSourceChip,
	suggestedGroups,
	suggestedGroupsLabel,
	suggestedGroupsList,
	groupChip,
	groupChipLabel,
	groupChipCount,
	weaponsSection,
	weaponsSectionLabel,
	noWeaponCard,
	noWeaponInfo,
	noWeaponLabel,
	noWeaponHint,
	cardList,
	conditionsSection,
	conditionsSectionHeader,
	conditionsSectionLabel,
	conditionAffectsToggle,
	conditionAffectsBtn,
	conditionAffectsBtnActive,
	conditionChips,
	conditionChip,
	conditionChipIcon,
	conditionChipLabel,
	conditionsTab,
	conditionAffectsRow,
	conditionAffectsRowLabel,
	conditionChipsFull,
	conditionChipFull,
	conditionChipFullIcon,
	conditionChipFullLabel,
	emptyState,
	shieldCard,
	shieldIcon,
	shieldLabel,
	shieldAc,
	panelFooter,
	companionsTab,
	companionCard,
	companionCardHeader,
	companionCardTypeIcon,
	companionCardName,
	companionCardTypeBadge,
	companionCardStats,
	companionCardStat,
	companionCardStatLabel,
	companionCardStatValue,
	companionCardMinLevel,
	addCustomBtn,
	modalOverlay,
	modal,
	modalHeader,
	modalTitle,
	closeBtn,
	modalForm,
	formLabel,
	formInput,
	formSelect,
	formTextarea,
	formActions,
	cancelBtn,
	submitBtn,
	dragHandle,
	dragHandleBar,
	panelOpen
};

declare const __default_export__: {
	panel: typeof panel;
	panelCollapsed: typeof panelCollapsed;
	panelSliver: typeof panelSliver;
	collapseBtn: typeof collapseBtn;
	sliverArrow: typeof sliverArrow;
	sliverLabel: typeof sliverLabel;
	panelHeader: typeof panelHeader;
	characterChip: typeof characterChip;
	classIcon: typeof classIcon;
	characterInfo: typeof characterInfo;
	characterClass: typeof characterClass;
	characterLevel: typeof characterLevel;
	templates: typeof templates;
	templatesLabel: typeof templatesLabel;
	templateGrid: typeof templateGrid;
	template: typeof template;
	templateIcon: typeof templateIcon;
	templateLabel: typeof templateLabel;
	searchWrapper: typeof searchWrapper;
	searchIcon: typeof searchIcon;
	searchInput: typeof searchInput;
	clearSearch: typeof clearSearch;
	tabs: typeof tabs;
	tab: typeof tab;
	activeTab: typeof activeTab;
	levelFilters: typeof levelFilters;
	levelChip: typeof levelChip;
	levelChipCircle: typeof levelChipCircle;
	activeLevelChip: typeof activeLevelChip;
	sourceFilters: typeof sourceFilters;
	sourceChip: typeof sourceChip;
	activeSourceChip: typeof activeSourceChip;
	suggestedGroups: typeof suggestedGroups;
	suggestedGroupsLabel: typeof suggestedGroupsLabel;
	suggestedGroupsList: typeof suggestedGroupsList;
	groupChip: typeof groupChip;
	groupChipLabel: typeof groupChipLabel;
	groupChipCount: typeof groupChipCount;
	weaponsSection: typeof weaponsSection;
	weaponsSectionLabel: typeof weaponsSectionLabel;
	noWeaponCard: typeof noWeaponCard;
	noWeaponInfo: typeof noWeaponInfo;
	noWeaponLabel: typeof noWeaponLabel;
	noWeaponHint: typeof noWeaponHint;
	cardList: typeof cardList;
	conditionsSection: typeof conditionsSection;
	conditionsSectionHeader: typeof conditionsSectionHeader;
	conditionsSectionLabel: typeof conditionsSectionLabel;
	conditionAffectsToggle: typeof conditionAffectsToggle;
	conditionAffectsBtn: typeof conditionAffectsBtn;
	conditionAffectsBtnActive: typeof conditionAffectsBtnActive;
	conditionChips: typeof conditionChips;
	conditionChip: typeof conditionChip;
	conditionChipIcon: typeof conditionChipIcon;
	conditionChipLabel: typeof conditionChipLabel;
	conditionsTab: typeof conditionsTab;
	conditionAffectsRow: typeof conditionAffectsRow;
	conditionAffectsRowLabel: typeof conditionAffectsRowLabel;
	conditionChipsFull: typeof conditionChipsFull;
	conditionChipFull: typeof conditionChipFull;
	conditionChipFullIcon: typeof conditionChipFullIcon;
	conditionChipFullLabel: typeof conditionChipFullLabel;
	emptyState: typeof emptyState;
	shieldCard: typeof shieldCard;
	shieldIcon: typeof shieldIcon;
	shieldLabel: typeof shieldLabel;
	shieldAc: typeof shieldAc;
	panelFooter: typeof panelFooter;
	companionsTab: typeof companionsTab;
	companionCard: typeof companionCard;
	companionCardHeader: typeof companionCardHeader;
	companionCardTypeIcon: typeof companionCardTypeIcon;
	companionCardName: typeof companionCardName;
	companionCardTypeBadge: typeof companionCardTypeBadge;
	companionCardStats: typeof companionCardStats;
	companionCardStat: typeof companionCardStat;
	companionCardStatLabel: typeof companionCardStatLabel;
	companionCardStatValue: typeof companionCardStatValue;
	companionCardMinLevel: typeof companionCardMinLevel;
	addCustomBtn: typeof addCustomBtn;
	modalOverlay: typeof modalOverlay;
	modal: typeof modal;
	modalHeader: typeof modalHeader;
	modalTitle: typeof modalTitle;
	closeBtn: typeof closeBtn;
	modalForm: typeof modalForm;
	formLabel: typeof formLabel;
	formInput: typeof formInput;
	formSelect: typeof formSelect;
	formTextarea: typeof formTextarea;
	formActions: typeof formActions;
	cancelBtn: typeof cancelBtn;
	submitBtn: typeof submitBtn;
	dragHandle: typeof dragHandle;
	dragHandleBar: typeof dragHandleBar;
	panelOpen: typeof panelOpen;
};
export default __default_export__;
