/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const card: string;
declare const cardTop: string;
declare const cardMeta: string;
declare const schoolBadge: string;
declare const levelBadge: string;
declare const sourceBadge: string;
declare const actionBadge: string;
declare const cardName: string;
declare const damageBadge: string;
declare const tooltip: string;
declare const tooltipHeader: string;
declare const tooltipName: string;
declare const tooltipType: string;
declare const tooltipMeta: string;
declare const tooltipDesc: string;
declare const tooltipHigher: string;
declare const ritualBadge: string;

export {
	card,
	cardTop,
	cardMeta,
	schoolBadge,
	levelBadge,
	sourceBadge,
	actionBadge,
	cardName,
	damageBadge,
	tooltip,
	tooltipHeader,
	tooltipName,
	tooltipType,
	tooltipMeta,
	tooltipDesc,
	tooltipHigher,
	ritualBadge
};

declare const __default_export__: {
	card: typeof card;
	cardTop: typeof cardTop;
	cardMeta: typeof cardMeta;
	schoolBadge: typeof schoolBadge;
	levelBadge: typeof levelBadge;
	sourceBadge: typeof sourceBadge;
	actionBadge: typeof actionBadge;
	cardName: typeof cardName;
	damageBadge: typeof damageBadge;
	tooltip: typeof tooltip;
	tooltipHeader: typeof tooltipHeader;
	tooltipName: typeof tooltipName;
	tooltipType: typeof tooltipType;
	tooltipMeta: typeof tooltipMeta;
	tooltipDesc: typeof tooltipDesc;
	tooltipHigher: typeof tooltipHigher;
	ritualBadge: typeof ritualBadge;
};
export default __default_export__;
