/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const overlay: string;
declare const panel: string;
declare const header: string;
declare const title: string;
declare const closeBtn: string;
declare const body: string;
declare const scoresGrid: string;
declare const scoreCell: string;
declare const scoreLabel: string;
declare const scoreInput: string;
declare const modifier: string;
declare const modifierPos: string;
declare const computedSection: string;
declare const computedTitle: string;
declare const computedRow: string;
declare const computedValue: string;
declare const footer: string;
declare const saveBtn: string;

export {
	overlay,
	panel,
	header,
	title,
	closeBtn,
	body,
	scoresGrid,
	scoreCell,
	scoreLabel,
	scoreInput,
	modifier,
	modifierPos,
	computedSection,
	computedTitle,
	computedRow,
	computedValue,
	footer,
	saveBtn
};

declare const __default_export__: {
	overlay: typeof overlay;
	panel: typeof panel;
	header: typeof header;
	title: typeof title;
	closeBtn: typeof closeBtn;
	body: typeof body;
	scoresGrid: typeof scoresGrid;
	scoreCell: typeof scoreCell;
	scoreLabel: typeof scoreLabel;
	scoreInput: typeof scoreInput;
	modifier: typeof modifier;
	modifierPos: typeof modifierPos;
	computedSection: typeof computedSection;
	computedTitle: typeof computedTitle;
	computedRow: typeof computedRow;
	computedValue: typeof computedValue;
	footer: typeof footer;
	saveBtn: typeof saveBtn;
};
export default __default_export__;
