/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const tabBar: string;
declare const tab: string;
declare const tabActive: string;
declare const tabIcon: string;
declare const tabInfo: string;
declare const tabName: string;
declare const tabMeta: string;
declare const tabClose: string;
declare const addTabBtn: string;
declare const modalOverlay: string;
declare const modal: string;
declare const modalTitle: string;
declare const modalList: string;
declare const modalItem: string;
declare const modalItemIcon: string;
declare const modalItemInfo: string;
declare const modalItemName: string;
declare const modalItemMeta: string;
declare const modalEmpty: string;
declare const modalClose: string;
declare const modalItemNew: string;
declare const modalDivider: string;

export {
	tabBar,
	tab,
	tabActive,
	tabIcon,
	tabInfo,
	tabName,
	tabMeta,
	tabClose,
	addTabBtn,
	modalOverlay,
	modal,
	modalTitle,
	modalList,
	modalItem,
	modalItemIcon,
	modalItemInfo,
	modalItemName,
	modalItemMeta,
	modalEmpty,
	modalClose,
	modalItemNew,
	modalDivider
};

declare const __default_export__: {
	tabBar: typeof tabBar;
	tab: typeof tab;
	tabActive: typeof tabActive;
	tabIcon: typeof tabIcon;
	tabInfo: typeof tabInfo;
	tabName: typeof tabName;
	tabMeta: typeof tabMeta;
	tabClose: typeof tabClose;
	addTabBtn: typeof addTabBtn;
	modalOverlay: typeof modalOverlay;
	modal: typeof modal;
	modalTitle: typeof modalTitle;
	modalList: typeof modalList;
	modalItem: typeof modalItem;
	modalItemIcon: typeof modalItemIcon;
	modalItemInfo: typeof modalItemInfo;
	modalItemName: typeof modalItemName;
	modalItemMeta: typeof modalItemMeta;
	modalEmpty: typeof modalEmpty;
	modalClose: typeof modalClose;
	modalItemNew: typeof modalItemNew;
	modalDivider: typeof modalDivider;
};
export default __default_export__;
