/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const card: string;
declare const cardTop: string;
declare const categoryBadge: string;
declare const martialTag: string;
declare const handBadgeMH: string;
declare const handBadgeOH: string;
declare const weaponIconBadge: string;
declare const cardName: string;
declare const cardPills: string;
declare const damagePill: string;
declare const rangePill: string;
declare const propTags: string;
declare const propTag: string;
declare const tooltip: string;
declare const tooltipHeader: string;
declare const tooltipName: string;
declare const tooltipType: string;
declare const tooltipMeta: string;

export {
	card,
	cardTop,
	categoryBadge,
	martialTag,
	handBadgeMH as handBadgeMh,
	handBadgeOH as handBadgeOh,
	weaponIconBadge,
	cardName,
	cardPills,
	damagePill,
	rangePill,
	propTags,
	propTag,
	tooltip,
	tooltipHeader,
	tooltipName,
	tooltipType,
	tooltipMeta
};

declare const __default_export__: {
	card: typeof card;
	cardTop: typeof cardTop;
	categoryBadge: typeof categoryBadge;
	martialTag: typeof martialTag;
	handBadgeMh: typeof handBadgeMH;
	handBadgeOh: typeof handBadgeOH;
	weaponIconBadge: typeof weaponIconBadge;
	cardName: typeof cardName;
	cardPills: typeof cardPills;
	damagePill: typeof damagePill;
	rangePill: typeof rangePill;
	propTags: typeof propTags;
	propTag: typeof propTag;
	tooltip: typeof tooltip;
	tooltipHeader: typeof tooltipHeader;
	tooltipName: typeof tooltipName;
	tooltipType: typeof tooltipType;
	tooltipMeta: typeof tooltipMeta;
};
export default __default_export__;
