/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const actionNode: string;
declare const selected: string;
declare const handle: string;
declare const header: string;
declare const badges: string;
declare const schoolBadge: string;
declare const levelBadge: string;
declare const handBadgeMH: string;
declare const handBadgeOH: string;
declare const actionTypeBadge: string;
declare const body: string;
declare const name: string;
declare const pills: string;
declare const damagePill: string;
declare const infoPill: string;
declare const componentPill: string;
declare const aoePill: string;
declare const notesSection: string;
declare const notesDisplay: string;
declare const notesText: string;
declare const notesPlaceholder: string;
declare const notesInput: string;
declare const diceRow: string;
declare const dicePill: string;
declare const savePill: string;
declare const saveDCValue: string;
declare const attackPill: string;
declare const attackBonusValue: string;
declare const higherLevels: string;
declare const scalesNote: string;
declare const concentrationBadge: string;
declare const ritualBadge: string;
declare const concentrationConflict: string;
declare const overBudget: string;
declare const resourceCostRow: string;
declare const resourceCostBadge: string;
declare const resourceCostAmount: string;
declare const castLevelRow: string;
declare const castLevelPill: string;
declare const castLevelPillActive: string;
declare const upcastBadge: string;
declare const critBadge: string;
declare const advantageBadge: string;
declare const disadvantageBadge: string;
declare const nodeTooltip: string;
declare const nodeTooltipHeader: string;
declare const nodeTooltipName: string;
declare const nodeTooltipType: string;
declare const nodeTooltipMeta: string;
declare const nodeTooltipDesc: string;
declare const nodeTooltipHigher: string;
declare const nodeTooltipNotes: string;

export {
	actionNode,
	selected,
	handle,
	header,
	badges,
	schoolBadge,
	levelBadge,
	handBadgeMH as handBadgeMh,
	handBadgeOH as handBadgeOh,
	actionTypeBadge,
	body,
	name,
	pills,
	damagePill,
	infoPill,
	componentPill,
	aoePill,
	notesSection,
	notesDisplay,
	notesText,
	notesPlaceholder,
	notesInput,
	diceRow,
	dicePill,
	savePill,
	saveDCValue as saveDcValue,
	attackPill,
	attackBonusValue,
	higherLevels,
	scalesNote,
	concentrationBadge,
	ritualBadge,
	concentrationConflict,
	overBudget,
	resourceCostRow,
	resourceCostBadge,
	resourceCostAmount,
	castLevelRow,
	castLevelPill,
	castLevelPillActive,
	upcastBadge,
	critBadge,
	advantageBadge,
	disadvantageBadge,
	nodeTooltip,
	nodeTooltipHeader,
	nodeTooltipName,
	nodeTooltipType,
	nodeTooltipMeta,
	nodeTooltipDesc,
	nodeTooltipHigher,
	nodeTooltipNotes
};

declare const __default_export__: {
	actionNode: typeof actionNode;
	selected: typeof selected;
	handle: typeof handle;
	header: typeof header;
	badges: typeof badges;
	schoolBadge: typeof schoolBadge;
	levelBadge: typeof levelBadge;
	handBadgeMh: typeof handBadgeMH;
	handBadgeOh: typeof handBadgeOH;
	actionTypeBadge: typeof actionTypeBadge;
	body: typeof body;
	name: typeof name;
	pills: typeof pills;
	damagePill: typeof damagePill;
	infoPill: typeof infoPill;
	componentPill: typeof componentPill;
	aoePill: typeof aoePill;
	notesSection: typeof notesSection;
	notesDisplay: typeof notesDisplay;
	notesText: typeof notesText;
	notesPlaceholder: typeof notesPlaceholder;
	notesInput: typeof notesInput;
	diceRow: typeof diceRow;
	dicePill: typeof dicePill;
	savePill: typeof savePill;
	saveDcValue: typeof saveDCValue;
	attackPill: typeof attackPill;
	attackBonusValue: typeof attackBonusValue;
	higherLevels: typeof higherLevels;
	scalesNote: typeof scalesNote;
	concentrationBadge: typeof concentrationBadge;
	ritualBadge: typeof ritualBadge;
	concentrationConflict: typeof concentrationConflict;
	overBudget: typeof overBudget;
	resourceCostRow: typeof resourceCostRow;
	resourceCostBadge: typeof resourceCostBadge;
	resourceCostAmount: typeof resourceCostAmount;
	castLevelRow: typeof castLevelRow;
	castLevelPill: typeof castLevelPill;
	castLevelPillActive: typeof castLevelPillActive;
	upcastBadge: typeof upcastBadge;
	critBadge: typeof critBadge;
	advantageBadge: typeof advantageBadge;
	disadvantageBadge: typeof disadvantageBadge;
	nodeTooltip: typeof nodeTooltip;
	nodeTooltipHeader: typeof nodeTooltipHeader;
	nodeTooltipName: typeof nodeTooltipName;
	nodeTooltipType: typeof nodeTooltipType;
	nodeTooltipMeta: typeof nodeTooltipMeta;
	nodeTooltipDesc: typeof nodeTooltipDesc;
	nodeTooltipHigher: typeof nodeTooltipHigher;
	nodeTooltipNotes: typeof nodeTooltipNotes;
};
export default __default_export__;
