/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const actionNode: string;
declare const selected: string;
declare const handle: string;
declare const header: string;
declare const badges: string;
declare const schoolBadge: string;
declare const levelBadge: string;
declare const handBadgeMH: string;
declare const handBadgeOH: string;
declare const actionTypeBadge: string;
declare const body: string;
declare const name: string;
declare const pills: string;
declare const damagePill: string;
declare const infoPill: string;
declare const notesSection: string;
declare const notesDisplay: string;
declare const notesText: string;
declare const notesPlaceholder: string;
declare const notesInput: string;
declare const diceRow: string;
declare const dicePill: string;
declare const savePill: string;
declare const saveDCValue: string;
declare const attackPill: string;
declare const higherLevels: string;
declare const concentrationBadge: string;
declare const concentrationConflict: string;
declare const overBudget: string;

export {
	actionNode,
	selected,
	handle,
	header,
	badges,
	schoolBadge,
	levelBadge,
	handBadgeMH as handBadgeMh,
	handBadgeOH as handBadgeOh,
	actionTypeBadge,
	body,
	name,
	pills,
	damagePill,
	infoPill,
	notesSection,
	notesDisplay,
	notesText,
	notesPlaceholder,
	notesInput,
	diceRow,
	dicePill,
	savePill,
	saveDCValue as saveDcValue,
	attackPill,
	higherLevels,
	concentrationBadge,
	concentrationConflict,
	overBudget
};

declare const __default_export__: {
	actionNode: typeof actionNode;
	selected: typeof selected;
	handle: typeof handle;
	header: typeof header;
	badges: typeof badges;
	schoolBadge: typeof schoolBadge;
	levelBadge: typeof levelBadge;
	handBadgeMh: typeof handBadgeMH;
	handBadgeOh: typeof handBadgeOH;
	actionTypeBadge: typeof actionTypeBadge;
	body: typeof body;
	name: typeof name;
	pills: typeof pills;
	damagePill: typeof damagePill;
	infoPill: typeof infoPill;
	notesSection: typeof notesSection;
	notesDisplay: typeof notesDisplay;
	notesText: typeof notesText;
	notesPlaceholder: typeof notesPlaceholder;
	notesInput: typeof notesInput;
	diceRow: typeof diceRow;
	dicePill: typeof dicePill;
	savePill: typeof savePill;
	saveDcValue: typeof saveDCValue;
	attackPill: typeof attackPill;
	higherLevels: typeof higherLevels;
	concentrationBadge: typeof concentrationBadge;
	concentrationConflict: typeof concentrationConflict;
	overBudget: typeof overBudget;
};
export default __default_export__;
