/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const companionNode: string;
declare const selected: string;
declare const handle: string;
declare const header: string;
declare const headerLeft: string;
declare const typeIcon: string;
declare const companionName: string;
declare const typeBadge: string;
declare const statsRow: string;
declare const stat: string;
declare const statLabel: string;
declare const statValue: string;
declare const statDivider: string;
declare const actionsContainer: string;
declare const actionsToggle: string;
declare const actionsToggleLabel: string;
declare const actionsToggleChevron: string;
declare const actionsList: string;
declare const actionRow: string;
declare const actionTypePip: string;
declare const actionName: string;
declare const actionDamage: string;
declare const notes: string;
declare const notesText: string;

export {
	companionNode,
	selected,
	handle,
	header,
	headerLeft,
	typeIcon,
	companionName,
	typeBadge,
	statsRow,
	stat,
	statLabel,
	statValue,
	statDivider,
	actionsContainer,
	actionsToggle,
	actionsToggleLabel,
	actionsToggleChevron,
	actionsList,
	actionRow,
	actionTypePip,
	actionName,
	actionDamage,
	notes,
	notesText
};

declare const __default_export__: {
	companionNode: typeof companionNode;
	selected: typeof selected;
	handle: typeof handle;
	header: typeof header;
	headerLeft: typeof headerLeft;
	typeIcon: typeof typeIcon;
	companionName: typeof companionName;
	typeBadge: typeof typeBadge;
	statsRow: typeof statsRow;
	stat: typeof stat;
	statLabel: typeof statLabel;
	statValue: typeof statValue;
	statDivider: typeof statDivider;
	actionsContainer: typeof actionsContainer;
	actionsToggle: typeof actionsToggle;
	actionsToggleLabel: typeof actionsToggleLabel;
	actionsToggleChevron: typeof actionsToggleChevron;
	actionsList: typeof actionsList;
	actionRow: typeof actionRow;
	actionTypePip: typeof actionTypePip;
	actionName: typeof actionName;
	actionDamage: typeof actionDamage;
	notes: typeof notes;
	notesText: typeof notesText;
};
export default __default_export__;
