/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const conditionNode: string;
declare const selected: string;
declare const inner: string;
declare const icon: string;
declare const labelDisplay: string;
declare const labelInput: string;
declare const branchLabels: string;
declare const yesLabel: string;
declare const noLabel: string;
declare const handle: string;
declare const yesHandle: string;
declare const noHandle: string;

export {
	conditionNode,
	selected,
	inner,
	icon,
	labelDisplay,
	labelInput,
	branchLabels,
	yesLabel,
	noLabel,
	handle,
	yesHandle,
	noHandle
};

declare const __default_export__: {
	conditionNode: typeof conditionNode;
	selected: typeof selected;
	inner: typeof inner;
	icon: typeof icon;
	labelDisplay: typeof labelDisplay;
	labelInput: typeof labelInput;
	branchLabels: typeof branchLabels;
	yesLabel: typeof yesLabel;
	noLabel: typeof noLabel;
	handle: typeof handle;
	yesHandle: typeof yesHandle;
	noHandle: typeof noHandle;
};
export default __default_export__;
