/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const node: string;
declare const selected: string;
declare const affectsTarget: string;
declare const affectsSelf: string;
declare const affectsArea: string;
declare const inner: string;
declare const icon: string;
declare const content: string;
declare const affectsLabel: string;
declare const label: string;
declare const labelInput: string;
declare const handle: string;

export {
	node,
	selected,
	affectsTarget,
	affectsSelf,
	affectsArea,
	inner,
	icon,
	content,
	affectsLabel,
	label,
	labelInput,
	handle
};

declare const __default_export__: {
	node: typeof node;
	selected: typeof selected;
	affectsTarget: typeof affectsTarget;
	affectsSelf: typeof affectsSelf;
	affectsArea: typeof affectsArea;
	inner: typeof inner;
	icon: typeof icon;
	content: typeof content;
	affectsLabel: typeof affectsLabel;
	label: typeof label;
	labelInput: typeof labelInput;
	handle: typeof handle;
};
export default __default_export__;
