/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const endNode: string;
declare const selected: string;
declare const inner: string;
declare const icon: string;
declare const label: string;
declare const labelInput: string;
declare const handle: string;

export {
	endNode,
	selected,
	inner,
	icon,
	label,
	labelInput,
	handle
};

declare const __default_export__: {
	endNode: typeof endNode;
	selected: typeof selected;
	inner: typeof inner;
	icon: typeof icon;
	label: typeof label;
	labelInput: typeof labelInput;
	handle: typeof handle;
};
export default __default_export__;
