/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const groupNode: string;
declare const selected: string;
declare const handle: string;
declare const header: string;
declare const headerLabel: string;
declare const labelInput: string;
declare const headerRight: string;
declare const countBadge: string;
declare const chevron: string;
declare const chevronCollapsed: string;
declare const variantList: string;
declare const collapsed: string;
declare const emptyHint: string;
declare const variantRow: string;
declare const variantRowTop: string;
declare const variantDot: string;
declare const variantLabel: string;
declare const variantBadges: string;
declare const schoolBadge: string;
declare const levelBadge: string;
declare const actionTypeBadge: string;
declare const damagePill: string;
declare const variantDetails: string;
declare const variantDetailPill: string;
declare const variantAttackPill: string;
declare const variantSavePill: string;
declare const variantHandle: string;
declare const bottomHandle: string;

export {
	groupNode,
	selected,
	handle,
	header,
	headerLabel,
	labelInput,
	headerRight,
	countBadge,
	chevron,
	chevronCollapsed,
	variantList,
	collapsed,
	emptyHint,
	variantRow,
	variantRowTop,
	variantDot,
	variantLabel,
	variantBadges,
	schoolBadge,
	levelBadge,
	actionTypeBadge,
	damagePill,
	variantDetails,
	variantDetailPill,
	variantAttackPill,
	variantSavePill,
	variantHandle,
	bottomHandle
};

declare const __default_export__: {
	groupNode: typeof groupNode;
	selected: typeof selected;
	handle: typeof handle;
	header: typeof header;
	headerLabel: typeof headerLabel;
	labelInput: typeof labelInput;
	headerRight: typeof headerRight;
	countBadge: typeof countBadge;
	chevron: typeof chevron;
	chevronCollapsed: typeof chevronCollapsed;
	variantList: typeof variantList;
	collapsed: typeof collapsed;
	emptyHint: typeof emptyHint;
	variantRow: typeof variantRow;
	variantRowTop: typeof variantRowTop;
	variantDot: typeof variantDot;
	variantLabel: typeof variantLabel;
	variantBadges: typeof variantBadges;
	schoolBadge: typeof schoolBadge;
	levelBadge: typeof levelBadge;
	actionTypeBadge: typeof actionTypeBadge;
	damagePill: typeof damagePill;
	variantDetails: typeof variantDetails;
	variantDetailPill: typeof variantDetailPill;
	variantAttackPill: typeof variantAttackPill;
	variantSavePill: typeof variantSavePill;
	variantHandle: typeof variantHandle;
	bottomHandle: typeof bottomHandle;
};
export default __default_export__;
