/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const noteNode: string;
declare const selected: string;
declare const corner: string;
declare const header: string;
declare const icon: string;
declare const title: string;
declare const textarea: string;

export {
	noteNode,
	selected,
	corner,
	header,
	icon,
	title,
	textarea
};

declare const __default_export__: {
	noteNode: typeof noteNode;
	selected: typeof selected;
	corner: typeof corner;
	header: typeof header;
	icon: typeof icon;
	title: typeof title;
	textarea: typeof textarea;
};
export default __default_export__;
